// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKg2Jb_LBD2pKYfaVbih_T_hqkNeuFUSQ',
    appId: '1:42191251749:web:4ae4c031bd3536bd7a92cc',
    messagingSenderId: '42191251749',
    projectId: 'dishdash-84c1b',
    authDomain: 'dishdash-84c1b.firebaseapp.com',
    storageBucket: 'dishdash-84c1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSwXE8KCw3c-hb4B9ILe6sLSvZih0Jp4g',
    appId: '1:42191251749:android:c7c348bd9b6d2f817a92cc',
    messagingSenderId: '42191251749',
    projectId: 'dishdash-84c1b',
    storageBucket: 'dishdash-84c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkG3hiIMQTuEzvbvck9qPLm_TPdo8dLLQ',
    appId: '1:42191251749:ios:cd0ae634d2f5655e7a92cc',
    messagingSenderId: '42191251749',
    projectId: 'dishdash-84c1b',
    storageBucket: 'dishdash-84c1b.firebasestorage.app',
    androidClientId: '42191251749-0l8i9vbumaqe7v1820j2brudqiq301j2.apps.googleusercontent.com',
    iosClientId: '42191251749-evat4o82p5vptjqglpqm6p5o0aftro6r.apps.googleusercontent.com',
    iosBundleId: 'com.eat.dishDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkG3hiIMQTuEzvbvck9qPLm_TPdo8dLLQ',
    appId: '1:42191251749:ios:241a64c29e208f207a92cc',
    messagingSenderId: '42191251749',
    projectId: 'dishdash-84c1b',
    storageBucket: 'dishdash-84c1b.firebasestorage.app',
    androidClientId: '42191251749-0l8i9vbumaqe7v1820j2brudqiq301j2.apps.googleusercontent.com',
    iosClientId: '42191251749-6nt6mgr111e1ajb070cspksra3jv40h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dishDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKg2Jb_LBD2pKYfaVbih_T_hqkNeuFUSQ',
    appId: '1:42191251749:web:452f068588db355b7a92cc',
    messagingSenderId: '42191251749',
    projectId: 'dishdash-84c1b',
    authDomain: 'dishdash-84c1b.firebaseapp.com',
    storageBucket: 'dishdash-84c1b.firebasestorage.app',
  );

}